import { Region } from "../ts/types.ts";

export const REGIONS: Region[] = [
  {
    "name": "Afghanistan",
    "alpha_2": "AF",
    "alpha_3": "AFG",
    "numeric_code": 4,
  },
  {
    "name": "Åland Islands",
    "alpha_2": "AX",
    "alpha_3": "ALA",
    "numeric_code": 248,
  },
  {
    "name": "Albania",
    "alpha_2": "AL",
    "alpha_3": "ALB",
    "numeric_code": 8,
  },
  {
    "name": "Algeria",
    "alpha_2": "DZ",
    "alpha_3": "DZA",
    "numeric_code": 12,
  },
  {
    "name": "American Samoa",
    "alpha_2": "AS",
    "alpha_3": "ASM",
    "numeric_code": 16,
  },
  {
    "name": "Andorra",
    "alpha_2": "AD",
    "alpha_3": "AND",
    "numeric_code": 20,
  },
  {
    "name": "Angola",
    "alpha_2": "AO",
    "alpha_3": "AGO",
    "numeric_code": 24,
  },
  {
    "name": "Anguilla",
    "alpha_2": "AI",
    "alpha_3": "AIA",
    "numeric_code": 660,
  },
  {
    "name": "Antarctica",
    "alpha_2": "AQ",
    "alpha_3": "ATA",
    "numeric_code": 10,
  },
  {
    "name": "Antigua and Barbuda",
    "alpha_2": "AG",
    "alpha_3": "ATG",
    "numeric_code": 28,
  },
  {
    "name": "Argentina",
    "alpha_2": "AR",
    "alpha_3": "ARG",
    "numeric_code": 32,
  },
  {
    "name": "Armenia",
    "alpha_2": "AM",
    "alpha_3": "ARM",
    "numeric_code": 51,
  },
  {
    "name": "Aruba",
    "alpha_2": "AW",
    "alpha_3": "ABW",
    "numeric_code": 533,
  },
  {
    "name": "Australia",
    "alpha_2": "AU",
    "alpha_3": "AUS",
    "numeric_code": 36,
  },
  {
    "name": "Austria",
    "alpha_2": "AT",
    "alpha_3": "AUT",
    "numeric_code": 40,
  },
  {
    "name": "Azerbaijan",
    "alpha_2": "AZ",
    "alpha_3": "AZE",
    "numeric_code": 31,
  },
  {
    "name": "Bahamas",
    "alpha_2": "BS",
    "alpha_3": "BHS",
    "numeric_code": 44,
  },
  {
    "name": "Bahrain",
    "alpha_2": "BH",
    "alpha_3": "BHR",
    "numeric_code": 48,
  },
  {
    "name": "Bangladesh",
    "alpha_2": "BD",
    "alpha_3": "BGD",
    "numeric_code": 50,
  },
  {
    "name": "Barbados",
    "alpha_2": "BB",
    "alpha_3": "BRB",
    "numeric_code": 52,
  },
  {
    "name": "Belarus",
    "alpha_2": "BY",
    "alpha_3": "BLR",
    "numeric_code": 112,
  },
  {
    "name": "Belgium",
    "alpha_2": "BE",
    "alpha_3": "BEL",
    "numeric_code": 56,
  },
  {
    "name": "Belize",
    "alpha_2": "BZ",
    "alpha_3": "BLZ",
    "numeric_code": 84,
  },
  {
    "name": "Benin",
    "alpha_2": "BJ",
    "alpha_3": "BEN",
    "numeric_code": 204,
  },
  {
    "name": "Bermuda",
    "alpha_2": "BM",
    "alpha_3": "BMU",
    "numeric_code": 60,
  },
  {
    "name": "Bhutan",
    "alpha_2": "BT",
    "alpha_3": "BTN",
    "numeric_code": 64,
  },
  {
    "name": "Bolivia (Plurinational State of)",
    "alpha_2": "BO",
    "alpha_3": "BOL",
    "numeric_code": 68,
  },
  {
    "name": "Bonaire, Sint Eustatius and Saba",
    "alpha_2": "BQ",
    "alpha_3": "BES",
    "numeric_code": 535,
  },
  {
    "name": "Bosnia and Herzegovina",
    "alpha_2": "BA",
    "alpha_3": "BIH",
    "numeric_code": 70,
  },
  {
    "name": "Botswana",
    "alpha_2": "BW",
    "alpha_3": "BWA",
    "numeric_code": 72,
  },
  {
    "name": "Bouvet Island",
    "alpha_2": "BV",
    "alpha_3": "BVT",
    "numeric_code": 74,
  },
  {
    "name": "Brazil",
    "alpha_2": "BR",
    "alpha_3": "BRA",
    "numeric_code": 76,
  },
  {
    "name": "British Indian Ocean Territory",
    "alpha_2": "IO",
    "alpha_3": "IOT",
    "numeric_code": 86,
  },
  {
    "name": "Brunei Darussalam",
    "alpha_2": "BN",
    "alpha_3": "BRN",
    "numeric_code": 96,
  },
  {
    "name": "Bulgaria",
    "alpha_2": "BG",
    "alpha_3": "BGR",
    "numeric_code": 100,
  },
  {
    "name": "Burkina Faso",
    "alpha_2": "BF",
    "alpha_3": "BFA",
    "numeric_code": 854,
  },
  {
    "name": "Burundi",
    "alpha_2": "BI",
    "alpha_3": "BDI",
    "numeric_code": 108,
  },
  {
    "name": "Cabo Verde",
    "alpha_2": "CV",
    "alpha_3": "CPV",
    "numeric_code": 132,
  },
  {
    "name": "Cambodia",
    "alpha_2": "KH",
    "alpha_3": "KHM",
    "numeric_code": 116,
  },
  {
    "name": "Cameroon",
    "alpha_2": "CM",
    "alpha_3": "CMR",
    "numeric_code": 120,
  },
  {
    "name": "Canada",
    "alpha_2": "CA",
    "alpha_3": "CAN",
    "numeric_code": 124,
  },
  {
    "name": "Cayman Islands",
    "alpha_2": "KY",
    "alpha_3": "CYM",
    "numeric_code": 136,
  },
  {
    "name": "Central African Republic",
    "alpha_2": "CF",
    "alpha_3": "CAF",
    "numeric_code": 140,
  },
  {
    "name": "Chad",
    "alpha_2": "TD",
    "alpha_3": "TCD",
    "numeric_code": 148,
  },
  {
    "name": "Chile",
    "alpha_2": "CL",
    "alpha_3": "CHL",
    "numeric_code": 152,
  },
  {
    "name": "China",
    "alpha_2": "CN",
    "alpha_3": "CHN",
    "numeric_code": 156,
  },
  {
    "name": "Christmas Island",
    "alpha_2": "CX",
    "alpha_3": "CXR",
    "numeric_code": 162,
  },
  {
    "name": "Cocos (Keeling) Islands",
    "alpha_2": "CC",
    "alpha_3": "CCK",
    "numeric_code": 166,
  },
  {
    "name": "Colombia",
    "alpha_2": "CO",
    "alpha_3": "COL",
    "numeric_code": 170,
  },
  {
    "name": "Comoros",
    "alpha_2": "KM",
    "alpha_3": "COM",
    "numeric_code": 174,
  },
  {
    "name": "Congo",
    "alpha_2": "CG",
    "alpha_3": "COG",
    "numeric_code": 178,
  },
  {
    "name": "Congo, Democratic Republic of the",
    "alpha_2": "CD",
    "alpha_3": "COD",
    "numeric_code": 180,
  },
  {
    "name": "Cook Islands",
    "alpha_2": "CK",
    "alpha_3": "COK",
    "numeric_code": 184,
  },
  {
    "name": "Costa Rica",
    "alpha_2": "CR",
    "alpha_3": "CRI",
    "numeric_code": 188,
  },
  {
    "name": "Côte d'Ivoire",
    "alpha_2": "CI",
    "alpha_3": "CIV",
    "numeric_code": 384,
  },
  {
    "name": "Croatia",
    "alpha_2": "HR",
    "alpha_3": "HRV",
    "numeric_code": 191,
  },
  {
    "name": "Cuba",
    "alpha_2": "CU",
    "alpha_3": "CUB",
    "numeric_code": 192,
  },
  {
    "name": "Curaçao",
    "alpha_2": "CW",
    "alpha_3": "CUW",
    "numeric_code": 531,
  },
  {
    "name": "Cyprus",
    "alpha_2": "CY",
    "alpha_3": "CYP",
    "numeric_code": 196,
  },
  {
    "name": "Czechia",
    "alpha_2": "CZ",
    "alpha_3": "CZE",
    "numeric_code": 203,
  },
  {
    "name": "Denmark",
    "alpha_2": "DK",
    "alpha_3": "DNK",
    "numeric_code": 208,
  },
  {
    "name": "Djibouti",
    "alpha_2": "DJ",
    "alpha_3": "DJI",
    "numeric_code": 262,
  },
  {
    "name": "Dominica",
    "alpha_2": "DM",
    "alpha_3": "DMA",
    "numeric_code": 212,
  },
  {
    "name": "Dominican Republic",
    "alpha_2": "DO",
    "alpha_3": "DOM",
    "numeric_code": 214,
  },
  {
    "name": "Ecuador",
    "alpha_2": "EC",
    "alpha_3": "ECU",
    "numeric_code": 218,
  },
  {
    "name": "Egypt",
    "alpha_2": "EG",
    "alpha_3": "EGY",
    "numeric_code": 818,
  },
  {
    "name": "El Salvador",
    "alpha_2": "SV",
    "alpha_3": "SLV",
    "numeric_code": 222,
  },
  {
    "name": "Equatorial Guinea",
    "alpha_2": "GQ",
    "alpha_3": "GNQ",
    "numeric_code": 226,
  },
  {
    "name": "Eritrea",
    "alpha_2": "ER",
    "alpha_3": "ERI",
    "numeric_code": 232,
  },
  {
    "name": "Estonia",
    "alpha_2": "EE",
    "alpha_3": "EST",
    "numeric_code": 233,
  },
  {
    "name": "Eswatini",
    "alpha_2": "SZ",
    "alpha_3": "SWZ",
    "numeric_code": 748,
  },
  {
    "name": "Ethiopia",
    "alpha_2": "ET",
    "alpha_3": "ETH",
    "numeric_code": 231,
  },
  {
    "name": "Falkland Islands (Malvinas)",
    "alpha_2": "FK",
    "alpha_3": "FLK",
    "numeric_code": 238,
  },
  {
    "name": "Faroe Islands",
    "alpha_2": "FO",
    "alpha_3": "FRO",
    "numeric_code": 234,
  },
  {
    "name": "Fiji",
    "alpha_2": "FJ",
    "alpha_3": "FJI",
    "numeric_code": 242,
  },
  {
    "name": "Finland",
    "alpha_2": "FI",
    "alpha_3": "FIN",
    "numeric_code": 246,
  },
  {
    "name": "France",
    "alpha_2": "FR",
    "alpha_3": "FRA",
    "numeric_code": 250,
  },
  {
    "name": "French Guiana",
    "alpha_2": "GF",
    "alpha_3": "GUF",
    "numeric_code": 254,
  },
  {
    "name": "French Polynesia",
    "alpha_2": "PF",
    "alpha_3": "PYF",
    "numeric_code": 258,
  },
  {
    "name": "French Southern Territories",
    "alpha_2": "TF",
    "alpha_3": "ATF",
    "numeric_code": 260,
  },
  {
    "name": "Gabon",
    "alpha_2": "GA",
    "alpha_3": "GAB",
    "numeric_code": 266,
  },
  {
    "name": "Gambia",
    "alpha_2": "GM",
    "alpha_3": "GMB",
    "numeric_code": 270,
  },
  {
    "name": "Georgia",
    "alpha_2": "GE",
    "alpha_3": "GEO",
    "numeric_code": 268,
  },
  {
    "name": "Germany",
    "alpha_2": "DE",
    "alpha_3": "DEU",
    "numeric_code": 276,
  },
  {
    "name": "Ghana",
    "alpha_2": "GH",
    "alpha_3": "GHA",
    "numeric_code": 288,
  },
  {
    "name": "Gibraltar",
    "alpha_2": "GI",
    "alpha_3": "GIB",
    "numeric_code": 292,
  },
  {
    "name": "Greece",
    "alpha_2": "GR",
    "alpha_3": "GRC",
    "numeric_code": 300,
  },
  {
    "name": "Greenland",
    "alpha_2": "GL",
    "alpha_3": "GRL",
    "numeric_code": 304,
  },
  {
    "name": "Grenada",
    "alpha_2": "GD",
    "alpha_3": "GRD",
    "numeric_code": 308,
  },
  {
    "name": "Guadeloupe",
    "alpha_2": "GP",
    "alpha_3": "GLP",
    "numeric_code": 312,
  },
  {
    "name": "Guam",
    "alpha_2": "GU",
    "alpha_3": "GUM",
    "numeric_code": 316,
  },
  {
    "name": "Guatemala",
    "alpha_2": "GT",
    "alpha_3": "GTM",
    "numeric_code": 320,
  },
  {
    "name": "Guernsey",
    "alpha_2": "GG",
    "alpha_3": "GGY",
    "numeric_code": 831,
  },
  {
    "name": "Guinea",
    "alpha_2": "GN",
    "alpha_3": "GIN",
    "numeric_code": 324,
  },
  {
    "name": "Guinea-Bissau",
    "alpha_2": "GW",
    "alpha_3": "GNB",
    "numeric_code": 624,
  },
  {
    "name": "Guyana",
    "alpha_2": "GY",
    "alpha_3": "GUY",
    "numeric_code": 328,
  },
  {
    "name": "Haiti",
    "alpha_2": "HT",
    "alpha_3": "HTI",
    "numeric_code": 332,
  },
  {
    "name": "Heard Island and McDonald Islands",
    "alpha_2": "HM",
    "alpha_3": "HMD",
    "numeric_code": 334,
  },
  {
    "name": "Holy See",
    "alpha_2": "VA",
    "alpha_3": "VAT",
    "numeric_code": 336,
  },
  {
    "name": "Honduras",
    "alpha_2": "HN",
    "alpha_3": "HND",
    "numeric_code": 340,
  },
  {
    "name": "Hong Kong",
    "alpha_2": "HK",
    "alpha_3": "HKG",
    "numeric_code": 344,
  },
  {
    "name": "Hungary",
    "alpha_2": "HU",
    "alpha_3": "HUN",
    "numeric_code": 348,
  },
  {
    "name": "Iceland",
    "alpha_2": "IS",
    "alpha_3": "ISL",
    "numeric_code": 352,
  },
  {
    "name": "India",
    "alpha_2": "IN",
    "alpha_3": "IND",
    "numeric_code": 356,
  },
  {
    "name": "Indonesia",
    "alpha_2": "ID",
    "alpha_3": "IDN",
    "numeric_code": 360,
  },
  {
    "name": "Iran (Islamic Republic of)",
    "alpha_2": "IR",
    "alpha_3": "IRN",
    "numeric_code": 364,
  },
  {
    "name": "Iraq",
    "alpha_2": "IQ",
    "alpha_3": "IRQ",
    "numeric_code": 368,
  },
  {
    "name": "Ireland",
    "alpha_2": "IE",
    "alpha_3": "IRL",
    "numeric_code": 372,
  },
  {
    "name": "Isle of Man",
    "alpha_2": "IM",
    "alpha_3": "IMN",
    "numeric_code": 833,
  },
  {
    "name": "Israel",
    "alpha_2": "IL",
    "alpha_3": "ISR",
    "numeric_code": 376,
  },
  {
    "name": "Italy",
    "alpha_2": "IT",
    "alpha_3": "ITA",
    "numeric_code": 380,
  },
  {
    "name": "Jamaica",
    "alpha_2": "JM",
    "alpha_3": "JAM",
    "numeric_code": 388,
  },
  {
    "name": "Japan",
    "alpha_2": "JP",
    "alpha_3": "JPN",
    "numeric_code": 392,
  },
  {
    "name": "Jersey",
    "alpha_2": "JE",
    "alpha_3": "JEY",
    "numeric_code": 832,
  },
  {
    "name": "Jordan",
    "alpha_2": "JO",
    "alpha_3": "JOR",
    "numeric_code": 400,
  },
  {
    "name": "Kazakhstan",
    "alpha_2": "KZ",
    "alpha_3": "KAZ",
    "numeric_code": 398,
  },
  {
    "name": "Kenya",
    "alpha_2": "KE",
    "alpha_3": "KEN",
    "numeric_code": 404,
  },
  {
    "name": "Kiribati",
    "alpha_2": "KI",
    "alpha_3": "KIR",
    "numeric_code": 296,
  },
  {
    "name": "Korea (Democratic People's Republic of)",
    "alpha_2": "KP",
    "alpha_3": "PRK",
    "numeric_code": 408,
  },
  {
    "name": "Korea, Republic of",
    "alpha_2": "KR",
    "alpha_3": "KOR",
    "numeric_code": 410,
  },
  {
    "name": "Kuwait",
    "alpha_2": "KW",
    "alpha_3": "KWT",
    "numeric_code": 414,
  },
  {
    "name": "Kyrgyzstan",
    "alpha_2": "KG",
    "alpha_3": "KGZ",
    "numeric_code": 417,
  },
  {
    "name": "Lao People's Democratic Republic",
    "alpha_2": "LA",
    "alpha_3": "LAO",
    "numeric_code": 418,
  },
  {
    "name": "Latvia",
    "alpha_2": "LV",
    "alpha_3": "LVA",
    "numeric_code": 428,
  },
  {
    "name": "Lebanon",
    "alpha_2": "LB",
    "alpha_3": "LBN",
    "numeric_code": 422,
  },
  {
    "name": "Lesotho",
    "alpha_2": "LS",
    "alpha_3": "LSO",
    "numeric_code": 426,
  },
  {
    "name": "Liberia",
    "alpha_2": "LR",
    "alpha_3": "LBR",
    "numeric_code": 430,
  },
  {
    "name": "Libya",
    "alpha_2": "LY",
    "alpha_3": "LBY",
    "numeric_code": 434,
  },
  {
    "name": "Liechtenstein",
    "alpha_2": "LI",
    "alpha_3": "LIE",
    "numeric_code": 438,
  },
  {
    "name": "Lithuania",
    "alpha_2": "LT",
    "alpha_3": "LTU",
    "numeric_code": 440,
  },
  {
    "name": "Luxembourg",
    "alpha_2": "LU",
    "alpha_3": "LUX",
    "numeric_code": 442,
  },
  {
    "name": "Macao",
    "alpha_2": "MO",
    "alpha_3": "MAC",
    "numeric_code": 446,
  },
  {
    "name": "Madagascar",
    "alpha_2": "MG",
    "alpha_3": "MDG",
    "numeric_code": 450,
  },
  {
    "name": "Malawi",
    "alpha_2": "MW",
    "alpha_3": "MWI",
    "numeric_code": 454,
  },
  {
    "name": "Malaysia",
    "alpha_2": "MY",
    "alpha_3": "MYS",
    "numeric_code": 458,
  },
  {
    "name": "Maldives",
    "alpha_2": "MV",
    "alpha_3": "MDV",
    "numeric_code": 462,
  },
  {
    "name": "Mali",
    "alpha_2": "ML",
    "alpha_3": "MLI",
    "numeric_code": 466,
  },
  {
    "name": "Malta",
    "alpha_2": "MT",
    "alpha_3": "MLT",
    "numeric_code": 470,
  },
  {
    "name": "Marshall Islands",
    "alpha_2": "MH",
    "alpha_3": "MHL",
    "numeric_code": 584,
  },
  {
    "name": "Martinique",
    "alpha_2": "MQ",
    "alpha_3": "MTQ",
    "numeric_code": 474,
  },
  {
    "name": "Mauritania",
    "alpha_2": "MR",
    "alpha_3": "MRT",
    "numeric_code": 478,
  },
  {
    "name": "Mauritius",
    "alpha_2": "MU",
    "alpha_3": "MUS",
    "numeric_code": 480,
  },
  {
    "name": "Mayotte",
    "alpha_2": "YT",
    "alpha_3": "MYT",
    "numeric_code": 175,
  },
  {
    "name": "Mexico",
    "alpha_2": "MX",
    "alpha_3": "MEX",
    "numeric_code": 484,
  },
  {
    "name": "Micronesia (Federated States of)",
    "alpha_2": "FM",
    "alpha_3": "FSM",
    "numeric_code": 583,
  },
  {
    "name": "Moldova, Republic of",
    "alpha_2": "MD",
    "alpha_3": "MDA",
    "numeric_code": 498,
  },
  {
    "name": "Monaco",
    "alpha_2": "MC",
    "alpha_3": "MCO",
    "numeric_code": 492,
  },
  {
    "name": "Mongolia",
    "alpha_2": "MN",
    "alpha_3": "MNG",
    "numeric_code": 496,
  },
  {
    "name": "Montenegro",
    "alpha_2": "ME",
    "alpha_3": "MNE",
    "numeric_code": 499,
  },
  {
    "name": "Montserrat",
    "alpha_2": "MS",
    "alpha_3": "MSR",
    "numeric_code": 500,
  },
  {
    "name": "Morocco",
    "alpha_2": "MA",
    "alpha_3": "MAR",
    "numeric_code": 504,
  },
  {
    "name": "Mozambique",
    "alpha_2": "MZ",
    "alpha_3": "MOZ",
    "numeric_code": 508,
  },
  {
    "name": "Myanmar",
    "alpha_2": "MM",
    "alpha_3": "MMR",
    "numeric_code": 104,
  },
  {
    "name": "Namibia",
    "alpha_2": "NA",
    "alpha_3": "NAM",
    "numeric_code": 516,
  },
  {
    "name": "Nauru",
    "alpha_2": "NR",
    "alpha_3": "NRU",
    "numeric_code": 520,
  },
  {
    "name": "Nepal",
    "alpha_2": "NP",
    "alpha_3": "NPL",
    "numeric_code": 524,
  },
  {
    "name": "Netherlands",
    "alpha_2": "NL",
    "alpha_3": "NLD",
    "numeric_code": 528,
  },
  {
    "name": "New Caledonia",
    "alpha_2": "NC",
    "alpha_3": "NCL",
    "numeric_code": 540,
  },
  {
    "name": "New Zealand",
    "alpha_2": "NZ",
    "alpha_3": "NZL",
    "numeric_code": 554,
  },
  {
    "name": "Nicaragua",
    "alpha_2": "NI",
    "alpha_3": "NIC",
    "numeric_code": 558,
  },
  {
    "name": "Niger",
    "alpha_2": "NE",
    "alpha_3": "NER",
    "numeric_code": 562,
  },
  {
    "name": "Nigeria",
    "alpha_2": "NG",
    "alpha_3": "NGA",
    "numeric_code": 566,
  },
  {
    "name": "Niue",
    "alpha_2": "NU",
    "alpha_3": "NIU",
    "numeric_code": 570,
  },
  {
    "name": "Norfolk Island",
    "alpha_2": "NF",
    "alpha_3": "NFK",
    "numeric_code": 574,
  },
  {
    "name": "North Macedonia",
    "alpha_2": "MK",
    "alpha_3": "MKD",
    "numeric_code": 807,
  },
  {
    "name": "Northern Mariana Islands",
    "alpha_2": "MP",
    "alpha_3": "MNP",
    "numeric_code": 580,
  },
  {
    "name": "Norway",
    "alpha_2": "NO",
    "alpha_3": "NOR",
    "numeric_code": 578,
  },
  {
    "name": "Oman",
    "alpha_2": "OM",
    "alpha_3": "OMN",
    "numeric_code": 512,
  },
  {
    "name": "Pakistan",
    "alpha_2": "PK",
    "alpha_3": "PAK",
    "numeric_code": 586,
  },
  {
    "name": "Palau",
    "alpha_2": "PW",
    "alpha_3": "PLW",
    "numeric_code": 585,
  },
  {
    "name": "Palestine, State of",
    "alpha_2": "PS",
    "alpha_3": "PSE",
    "numeric_code": 275,
  },
  {
    "name": "Panama",
    "alpha_2": "PA",
    "alpha_3": "PAN",
    "numeric_code": 591,
  },
  {
    "name": "Papua New Guinea",
    "alpha_2": "PG",
    "alpha_3": "PNG",
    "numeric_code": 598,
  },
  {
    "name": "Paraguay",
    "alpha_2": "PY",
    "alpha_3": "PRY",
    "numeric_code": 600,
  },
  {
    "name": "Peru",
    "alpha_2": "PE",
    "alpha_3": "PER",
    "numeric_code": 604,
  },
  {
    "name": "Philippines",
    "alpha_2": "PH",
    "alpha_3": "PHL",
    "numeric_code": 608,
  },
  {
    "name": "Pitcairn",
    "alpha_2": "PN",
    "alpha_3": "PCN",
    "numeric_code": 612,
  },
  {
    "name": "Poland",
    "alpha_2": "PL",
    "alpha_3": "POL",
    "numeric_code": 616,
  },
  {
    "name": "Portugal",
    "alpha_2": "PT",
    "alpha_3": "PRT",
    "numeric_code": 620,
  },
  {
    "name": "Puerto Rico",
    "alpha_2": "PR",
    "alpha_3": "PRI",
    "numeric_code": 630,
  },
  {
    "name": "Qatar",
    "alpha_2": "QA",
    "alpha_3": "QAT",
    "numeric_code": 634,
  },
  {
    "name": "Réunion",
    "alpha_2": "RE",
    "alpha_3": "REU",
    "numeric_code": 638,
  },
  {
    "name": "Romania",
    "alpha_2": "RO",
    "alpha_3": "ROU",
    "numeric_code": 642,
  },
  {
    "name": "russia",
    "alpha_2": "RU",
    "alpha_3": "RUS",
    "numeric_code": 643,
  },
  {
    "name": "Rwanda",
    "alpha_2": "RW",
    "alpha_3": "RWA",
    "numeric_code": 646,
  },
  {
    "name": "Saint Barthélemy",
    "alpha_2": "BL",
    "alpha_3": "BLM",
    "numeric_code": 652,
  },
  {
    "name": "Saint Helena, Ascension and Tristan da Cunha",
    "alpha_2": "SH",
    "alpha_3": "SHN",
    "numeric_code": 654,
  },
  {
    "name": "Saint Kitts and Nevis",
    "alpha_2": "KN",
    "alpha_3": "KNA",
    "numeric_code": 659,
  },
  {
    "name": "Saint Lucia",
    "alpha_2": "LC",
    "alpha_3": "LCA",
    "numeric_code": 662,
  },
  {
    "name": "Saint Martin (French part)",
    "alpha_2": "MF",
    "alpha_3": "MAF",
    "numeric_code": 663,
  },
  {
    "name": "Saint Pierre and Miquelon",
    "alpha_2": "PM",
    "alpha_3": "SPM",
    "numeric_code": 666,
  },
  {
    "name": "Saint Vincent and the Grenadines",
    "alpha_2": "VC",
    "alpha_3": "VCT",
    "numeric_code": 670,
  },
  {
    "name": "Samoa",
    "alpha_2": "WS",
    "alpha_3": "WSM",
    "numeric_code": 882,
  },
  {
    "name": "San Marino",
    "alpha_2": "SM",
    "alpha_3": "SMR",
    "numeric_code": 674,
  },
  {
    "name": "Sao Tome and Principe",
    "alpha_2": "ST",
    "alpha_3": "STP",
    "numeric_code": 678,
  },
  {
    "name": "Saudi Arabia",
    "alpha_2": "SA",
    "alpha_3": "SAU",
    "numeric_code": 682,
  },
  {
    "name": "Senegal",
    "alpha_2": "SN",
    "alpha_3": "SEN",
    "numeric_code": 686,
  },
  {
    "name": "Serbia",
    "alpha_2": "RS",
    "alpha_3": "SRB",
    "numeric_code": 688,
  },
  {
    "name": "Seychelles",
    "alpha_2": "SC",
    "alpha_3": "SYC",
    "numeric_code": 690,
  },
  {
    "name": "Sierra Leone",
    "alpha_2": "SL",
    "alpha_3": "SLE",
    "numeric_code": 694,
  },
  {
    "name": "Singapore",
    "alpha_2": "SG",
    "alpha_3": "SGP",
    "numeric_code": 702,
  },
  {
    "name": "Sint Maarten (Dutch part)",
    "alpha_2": "SX",
    "alpha_3": "SXM",
    "numeric_code": 534,
  },
  {
    "name": "Slovakia",
    "alpha_2": "SK",
    "alpha_3": "SVK",
    "numeric_code": 703,
  },
  {
    "name": "Slovenia",
    "alpha_2": "SI",
    "alpha_3": "SVN",
    "numeric_code": 705,
  },
  {
    "name": "Solomon Islands",
    "alpha_2": "SB",
    "alpha_3": "SLB",
    "numeric_code": 90,
  },
  {
    "name": "Somalia",
    "alpha_2": "SO",
    "alpha_3": "SOM",
    "numeric_code": 706,
  },
  {
    "name": "South Africa",
    "alpha_2": "ZA",
    "alpha_3": "ZAF",
    "numeric_code": 710,
  },
  {
    "name": "South Georgia and the South Sandwich Islands",
    "alpha_2": "GS",
    "alpha_3": "SGS",
    "numeric_code": 239,
  },
  {
    "name": "South Sudan",
    "alpha_2": "SS",
    "alpha_3": "SSD",
    "numeric_code": 728,
  },
  {
    "name": "Spain",
    "alpha_2": "ES",
    "alpha_3": "ESP",
    "numeric_code": 724,
  },
  {
    "name": "Sri Lanka",
    "alpha_2": "LK",
    "alpha_3": "LKA",
    "numeric_code": 144,
  },
  {
    "name": "Sudan",
    "alpha_2": "SD",
    "alpha_3": "SDN",
    "numeric_code": 729,
  },
  {
    "name": "Suriname",
    "alpha_2": "SR",
    "alpha_3": "SUR",
    "numeric_code": 740,
  },
  {
    "name": "Svalbard and Jan Mayen",
    "alpha_2": "SJ",
    "alpha_3": "SJM",
    "numeric_code": 744,
  },
  {
    "name": "Sweden",
    "alpha_2": "SE",
    "alpha_3": "SWE",
    "numeric_code": 752,
  },
  {
    "name": "Switzerland",
    "alpha_2": "CH",
    "alpha_3": "CHE",
    "numeric_code": 756,
  },
  {
    "name": "Syrian Arab Republic",
    "alpha_2": "SY",
    "alpha_3": "SYR",
    "numeric_code": 760,
  },
  {
    "name": "Taiwan, Province of China",
    "alpha_2": "TW",
    "alpha_3": "TWN",
    "numeric_code": 158,
  },
  {
    "name": "Tajikistan",
    "alpha_2": "TJ",
    "alpha_3": "TJK",
    "numeric_code": 762,
  },
  {
    "name": "Tanzania, United Republic of",
    "alpha_2": "TZ",
    "alpha_3": "TZA",
    "numeric_code": 834,
  },
  {
    "name": "Thailand",
    "alpha_2": "TH",
    "alpha_3": "THA",
    "numeric_code": 764,
  },
  {
    "name": "Timor-Leste",
    "alpha_2": "TL",
    "alpha_3": "TLS",
    "numeric_code": 626,
  },
  {
    "name": "Togo",
    "alpha_2": "TG",
    "alpha_3": "TGO",
    "numeric_code": 768,
  },
  {
    "name": "Tokelau",
    "alpha_2": "TK",
    "alpha_3": "TKL",
    "numeric_code": 772,
  },
  {
    "name": "Tonga",
    "alpha_2": "TO",
    "alpha_3": "TON",
    "numeric_code": 776,
  },
  {
    "name": "Trinidad and Tobago",
    "alpha_2": "TT",
    "alpha_3": "TTO",
    "numeric_code": 780,
  },
  {
    "name": "Tunisia",
    "alpha_2": "TN",
    "alpha_3": "TUN",
    "numeric_code": 788,
  },
  {
    "name": "Turkey",
    "alpha_2": "TR",
    "alpha_3": "TUR",
    "numeric_code": 792,
  },
  {
    "name": "Turkmenistan",
    "alpha_2": "TM",
    "alpha_3": "TKM",
    "numeric_code": 795,
  },
  {
    "name": "Turks and Caicos Islands",
    "alpha_2": "TC",
    "alpha_3": "TCA",
    "numeric_code": 796,
  },
  {
    "name": "Tuvalu",
    "alpha_2": "TV",
    "alpha_3": "TUV",
    "numeric_code": 798,
  },
  {
    "name": "Uganda",
    "alpha_2": "UG",
    "alpha_3": "UGA",
    "numeric_code": 800,
  },
  {
    "name": "Ukraine",
    "alpha_2": "UA",
    "alpha_3": "UKR",
    "numeric_code": 804,
  },
  {
    "name": "United Arab Emirates",
    "alpha_2": "AE",
    "alpha_3": "ARE",
    "numeric_code": 784,
  },
  {
    "name": "United Kingdom of Great Britain and Northern Ireland",
    "alpha_2": "GB",
    "alpha_3": "GBR",
    "numeric_code": 826,
  },
  {
    "name": "United States of America",
    "alpha_2": "US",
    "alpha_3": "USA",
    "numeric_code": 840,
  },
  {
    "name": "United States Minor Outlying Islands",
    "alpha_2": "UM",
    "alpha_3": "UMI",
    "numeric_code": 581,
  },
  {
    "name": "Uruguay",
    "alpha_2": "UY",
    "alpha_3": "URY",
    "numeric_code": 858,
  },
  {
    "name": "Uzbekistan",
    "alpha_2": "UZ",
    "alpha_3": "UZB",
    "numeric_code": 860,
  },
  {
    "name": "Vanuatu",
    "alpha_2": "VU",
    "alpha_3": "VUT",
    "numeric_code": 548,
  },
  {
    "name": "Venezuela (Bolivarian Republic of)",
    "alpha_2": "VE",
    "alpha_3": "VEN",
    "numeric_code": 862,
  },
  {
    "name": "Viet Nam",
    "alpha_2": "VN",
    "alpha_3": "VNM",
    "numeric_code": 704,
  },
  {
    "name": "Virgin Islands (British)",
    "alpha_2": "VG",
    "alpha_3": "VGB",
    "numeric_code": 92,
  },
  {
    "name": "Virgin Islands (U.S.)",
    "alpha_2": "VI",
    "alpha_3": "VIR",
    "numeric_code": 850,
  },
  {
    "name": "Wallis and Futuna",
    "alpha_2": "WF",
    "alpha_3": "WLF",
    "numeric_code": 876,
  },
  {
    "name": "Western Sahara",
    "alpha_2": "EH",
    "alpha_3": "ESH",
    "numeric_code": 732,
  },
  {
    "name": "Yemen",
    "alpha_2": "YE",
    "alpha_3": "YEM",
    "numeric_code": 887,
  },
  {
    "name": "Zambia",
    "alpha_2": "ZM",
    "alpha_3": "ZMB",
    "numeric_code": 894,
  },
  {
    "name": "Zimbabwe",
    "alpha_2": "ZW",
    "alpha_3": "ZWE",
    "numeric_code": 716,
  },
];
